Tried to add e2e tests with jest - failed
 /versioned/utily/smoothly/node_modules/cloudly-http/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { Client } from "./Client";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module